# ~/observability-stack/loki/loki-config.yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki/data
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory # For testing/dev; use 'consul' or 'etcd' for HA in production

# Use tsdb for the index store, which is recommended for modern Loki features
# and structured metadata.
storage_config:
  tsdb_shipper: # Changed from boltdb_shipper
    active_index_directory: /loki/data/tsdb-shipper-active
    cache_location: /loki/data/tsdb-shipper-cache
    resync_interval: 5s
  filesystem:
    directory: /loki/data/chunks # Directory for log chunks

schema_config:
  configs:
    - from: 2020-10-24 # Date from which this schema applies
      store: tsdb # Changed from boltdb-shipper
      object_store: filesystem
      schema: v13 # Changed from v11
      index: # Added index configuration explicitly for TSDB
        period: 24h # Recommended period for index
        prefix: index_

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 168h # 7 days
  max_chunk_age: 1h

# Add limits_config to allow structured metadata if schema v13/tsdb is used,
# or to disable it if sticking to v11/boltdb-shipper
limits_config:
  # Set to true if you want to explicitly allow structured metadata with new schema/index type.
  # If you keep v11/boltdb-shipper, set this to 'false' to silence the warnings.
  allow_structured_metadata: true