# ~/observability-stack/grafana/datasources/loki.yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDataSource

metadata:
  name: loki-datasource

spec:
  datasources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100 # Loki está accesible por su nombre de servicio dentro de la red Docker
      basicAuth: false
      isDefault: false # Puedes cambiar a true si quieres que Loki sea la fuente por defecto
      version: 1
      editable: true